apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: enkins/jenkins:lts-jdk17
        ports:
        - containerPort: 8080
      volumeMounts: 
      - name: jenkins-pv
          mountPath: /var/jenkins_home
    volumes: 
    - name: jenkins-pv
      emptyDir: { }